package com.pipimovie.dataobject;

public class AdminDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_admin.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_admin.name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_admin.password
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_admin.logincount
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short logincount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_admin.loginip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String loginip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_admin.logintime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer logintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_admin.groupid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_admin.state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short state;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_admin
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public AdminDO(Integer id, String name, String password, Short logincount, String loginip, Integer logintime, Short groupid, Short state) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.logincount = logincount;
        this.loginip = loginip;
        this.logintime = logintime;
        this.groupid = groupid;
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_admin
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public AdminDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_admin.id
     *
     * @return the value of sea_admin.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_admin.id
     *
     * @param id the value for sea_admin.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_admin.name
     *
     * @return the value of sea_admin.name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_admin.name
     *
     * @param name the value for sea_admin.name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_admin.password
     *
     * @return the value of sea_admin.password
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_admin.password
     *
     * @param password the value for sea_admin.password
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_admin.logincount
     *
     * @return the value of sea_admin.logincount
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getLogincount() {
        return logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_admin.logincount
     *
     * @param logincount the value for sea_admin.logincount
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setLogincount(Short logincount) {
        this.logincount = logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_admin.loginip
     *
     * @return the value of sea_admin.loginip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_admin.loginip
     *
     * @param loginip the value for sea_admin.loginip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip == null ? null : loginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_admin.logintime
     *
     * @return the value of sea_admin.logintime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_admin.logintime
     *
     * @param logintime the value for sea_admin.logintime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setLogintime(Integer logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_admin.groupid
     *
     * @return the value of sea_admin.groupid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_admin.groupid
     *
     * @param groupid the value for sea_admin.groupid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setGroupid(Short groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_admin.state
     *
     * @return the value of sea_admin.state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_admin.state
     *
     * @param state the value for sea_admin.state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setState(Short state) {
        this.state = state;
    }
}