package com.pipimovie.dataobject;

import java.util.Date;

public class CCKDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_cck.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_cck.ckey
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String ckey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_cck.climit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer climit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_cck.maketime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Date maketime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_cck.usetime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Date usetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_cck.uname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_cck.status
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_cck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CCKDO(Integer id, String ckey, Integer climit, Date maketime, Date usetime, String uname, String status) {
        this.id = id;
        this.ckey = ckey;
        this.climit = climit;
        this.maketime = maketime;
        this.usetime = usetime;
        this.uname = uname;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_cck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CCKDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_cck.id
     *
     * @return the value of sea_cck.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_cck.id
     *
     * @param id the value for sea_cck.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_cck.ckey
     *
     * @return the value of sea_cck.ckey
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getCkey() {
        return ckey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_cck.ckey
     *
     * @param ckey the value for sea_cck.ckey
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCkey(String ckey) {
        this.ckey = ckey == null ? null : ckey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_cck.climit
     *
     * @return the value of sea_cck.climit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getClimit() {
        return climit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_cck.climit
     *
     * @param climit the value for sea_cck.climit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setClimit(Integer climit) {
        this.climit = climit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_cck.maketime
     *
     * @return the value of sea_cck.maketime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Date getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_cck.maketime
     *
     * @param maketime the value for sea_cck.maketime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_cck.usetime
     *
     * @return the value of sea_cck.usetime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Date getUsetime() {
        return usetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_cck.usetime
     *
     * @param usetime the value for sea_cck.usetime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setUsetime(Date usetime) {
        this.usetime = usetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_cck.uname
     *
     * @return the value of sea_cck.uname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_cck.uname
     *
     * @param uname the value for sea_cck.uname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_cck.status
     *
     * @return the value of sea_cck.status
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_cck.status
     *
     * @param status the value for sea_cck.status
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}