package com.pipimovie.dataobject;

public class CoclsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_cls.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_cls.clsname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String clsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_cls.sysclsid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short sysclsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_cls.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Byte cotype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_cls
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CoclsDO(Integer id, String clsname, Short sysclsid, Byte cotype) {
        this.id = id;
        this.clsname = clsname;
        this.sysclsid = sysclsid;
        this.cotype = cotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_cls
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CoclsDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_cls.id
     *
     * @return the value of sea_co_cls.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_cls.id
     *
     * @param id the value for sea_co_cls.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_cls.clsname
     *
     * @return the value of sea_co_cls.clsname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getClsname() {
        return clsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_cls.clsname
     *
     * @param clsname the value for sea_co_cls.clsname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setClsname(String clsname) {
        this.clsname = clsname == null ? null : clsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_cls.sysclsid
     *
     * @return the value of sea_co_cls.sysclsid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getSysclsid() {
        return sysclsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_cls.sysclsid
     *
     * @param sysclsid the value for sea_co_cls.sysclsid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setSysclsid(Short sysclsid) {
        this.sysclsid = sysclsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_cls.cotype
     *
     * @return the value of sea_co_cls.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Byte getCotype() {
        return cotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_cls.cotype
     *
     * @param cotype the value for sea_co_cls.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCotype(Byte cotype) {
        this.cotype = cotype;
    }
}