package com.pipimovie.dataobject;

public class CoconfigDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_config.cid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_config.cname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_config.getlistnum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer getlistnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_config.getconnum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer getconnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_config.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Byte cotype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_config
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CoconfigDO(Integer cid, String cname, Integer getlistnum, Integer getconnum, Byte cotype) {
        this.cid = cid;
        this.cname = cname;
        this.getlistnum = getlistnum;
        this.getconnum = getconnum;
        this.cotype = cotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_config
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CoconfigDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_config.cid
     *
     * @return the value of sea_co_config.cid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_config.cid
     *
     * @param cid the value for sea_co_config.cid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_config.cname
     *
     * @return the value of sea_co_config.cname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_config.cname
     *
     * @param cname the value for sea_co_config.cname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_config.getlistnum
     *
     * @return the value of sea_co_config.getlistnum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getGetlistnum() {
        return getlistnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_config.getlistnum
     *
     * @param getlistnum the value for sea_co_config.getlistnum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setGetlistnum(Integer getlistnum) {
        this.getlistnum = getlistnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_config.getconnum
     *
     * @return the value of sea_co_config.getconnum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getGetconnum() {
        return getconnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_config.getconnum
     *
     * @param getconnum the value for sea_co_config.getconnum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setGetconnum(Integer getconnum) {
        this.getconnum = getconnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_config.cotype
     *
     * @return the value of sea_co_config.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Byte getCotype() {
        return cotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_config.cotype
     *
     * @param cotype the value for sea_co_config.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCotype(Byte cotype) {
        this.cotype = cotype;
    }
}