package com.pipimovie.dataobject;

public class CodataDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_spic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vSpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_gpic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vGpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vHit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_money
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_rank
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_digg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vDigg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_tread
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vTread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_commend
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vCommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_wrong
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vWrong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_director
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vDirector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_enname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vEnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_lang
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vLang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_actor
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vActor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_color
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_publishyear
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vPublishyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_publisharea
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vPublisharea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vAddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vTags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_from
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_data.v_inbase
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vInbase;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_data
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CodataDO(Integer vId, Short tid, String tname, String vName, Integer vState, String vPic, String vSpic, String vGpic, Integer vHit, Short vMoney, Short vRank, Short vDigg, Short vTread, Short vCommend, Short vWrong, String vDirector, String vEnname, String vLang, String vActor, String vColor, String vPublishyear, String vPublisharea, Integer vAddtime, Integer vTopic, String vNote, String vTags, String vLetter, String vFrom, String vInbase) {
        this.vId = vId;
        this.tid = tid;
        this.tname = tname;
        this.vName = vName;
        this.vState = vState;
        this.vPic = vPic;
        this.vSpic = vSpic;
        this.vGpic = vGpic;
        this.vHit = vHit;
        this.vMoney = vMoney;
        this.vRank = vRank;
        this.vDigg = vDigg;
        this.vTread = vTread;
        this.vCommend = vCommend;
        this.vWrong = vWrong;
        this.vDirector = vDirector;
        this.vEnname = vEnname;
        this.vLang = vLang;
        this.vActor = vActor;
        this.vColor = vColor;
        this.vPublishyear = vPublishyear;
        this.vPublisharea = vPublisharea;
        this.vAddtime = vAddtime;
        this.vTopic = vTopic;
        this.vNote = vNote;
        this.vTags = vTags;
        this.vLetter = vLetter;
        this.vFrom = vFrom;
        this.vInbase = vInbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_data
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CodataDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_id
     *
     * @return the value of sea_co_data.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_id
     *
     * @param vId the value for sea_co_data.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvId(Integer vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.tid
     *
     * @return the value of sea_co_data.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.tid
     *
     * @param tid the value for sea_co_data.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTid(Short tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.tname
     *
     * @return the value of sea_co_data.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.tname
     *
     * @param tname the value for sea_co_data.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_name
     *
     * @return the value of sea_co_data.v_name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvName() {
        return vName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_name
     *
     * @param vName the value for sea_co_data.v_name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvName(String vName) {
        this.vName = vName == null ? null : vName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_state
     *
     * @return the value of sea_co_data.v_state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvState() {
        return vState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_state
     *
     * @param vState the value for sea_co_data.v_state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvState(Integer vState) {
        this.vState = vState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_pic
     *
     * @return the value of sea_co_data.v_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvPic() {
        return vPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_pic
     *
     * @param vPic the value for sea_co_data.v_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvPic(String vPic) {
        this.vPic = vPic == null ? null : vPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_spic
     *
     * @return the value of sea_co_data.v_spic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvSpic() {
        return vSpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_spic
     *
     * @param vSpic the value for sea_co_data.v_spic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvSpic(String vSpic) {
        this.vSpic = vSpic == null ? null : vSpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_gpic
     *
     * @return the value of sea_co_data.v_gpic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvGpic() {
        return vGpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_gpic
     *
     * @param vGpic the value for sea_co_data.v_gpic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvGpic(String vGpic) {
        this.vGpic = vGpic == null ? null : vGpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_hit
     *
     * @return the value of sea_co_data.v_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvHit() {
        return vHit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_hit
     *
     * @param vHit the value for sea_co_data.v_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvHit(Integer vHit) {
        this.vHit = vHit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_money
     *
     * @return the value of sea_co_data.v_money
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvMoney() {
        return vMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_money
     *
     * @param vMoney the value for sea_co_data.v_money
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvMoney(Short vMoney) {
        this.vMoney = vMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_rank
     *
     * @return the value of sea_co_data.v_rank
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvRank() {
        return vRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_rank
     *
     * @param vRank the value for sea_co_data.v_rank
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvRank(Short vRank) {
        this.vRank = vRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_digg
     *
     * @return the value of sea_co_data.v_digg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvDigg() {
        return vDigg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_digg
     *
     * @param vDigg the value for sea_co_data.v_digg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvDigg(Short vDigg) {
        this.vDigg = vDigg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_tread
     *
     * @return the value of sea_co_data.v_tread
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvTread() {
        return vTread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_tread
     *
     * @param vTread the value for sea_co_data.v_tread
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvTread(Short vTread) {
        this.vTread = vTread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_commend
     *
     * @return the value of sea_co_data.v_commend
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvCommend() {
        return vCommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_commend
     *
     * @param vCommend the value for sea_co_data.v_commend
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvCommend(Short vCommend) {
        this.vCommend = vCommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_wrong
     *
     * @return the value of sea_co_data.v_wrong
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvWrong() {
        return vWrong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_wrong
     *
     * @param vWrong the value for sea_co_data.v_wrong
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvWrong(Short vWrong) {
        this.vWrong = vWrong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_director
     *
     * @return the value of sea_co_data.v_director
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvDirector() {
        return vDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_director
     *
     * @param vDirector the value for sea_co_data.v_director
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvDirector(String vDirector) {
        this.vDirector = vDirector == null ? null : vDirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_enname
     *
     * @return the value of sea_co_data.v_enname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvEnname() {
        return vEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_enname
     *
     * @param vEnname the value for sea_co_data.v_enname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvEnname(String vEnname) {
        this.vEnname = vEnname == null ? null : vEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_lang
     *
     * @return the value of sea_co_data.v_lang
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvLang() {
        return vLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_lang
     *
     * @param vLang the value for sea_co_data.v_lang
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvLang(String vLang) {
        this.vLang = vLang == null ? null : vLang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_actor
     *
     * @return the value of sea_co_data.v_actor
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvActor() {
        return vActor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_actor
     *
     * @param vActor the value for sea_co_data.v_actor
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvActor(String vActor) {
        this.vActor = vActor == null ? null : vActor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_color
     *
     * @return the value of sea_co_data.v_color
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvColor() {
        return vColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_color
     *
     * @param vColor the value for sea_co_data.v_color
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvColor(String vColor) {
        this.vColor = vColor == null ? null : vColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_publishyear
     *
     * @return the value of sea_co_data.v_publishyear
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvPublishyear() {
        return vPublishyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_publishyear
     *
     * @param vPublishyear the value for sea_co_data.v_publishyear
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvPublishyear(String vPublishyear) {
        this.vPublishyear = vPublishyear == null ? null : vPublishyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_publisharea
     *
     * @return the value of sea_co_data.v_publisharea
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvPublisharea() {
        return vPublisharea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_publisharea
     *
     * @param vPublisharea the value for sea_co_data.v_publisharea
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvPublisharea(String vPublisharea) {
        this.vPublisharea = vPublisharea == null ? null : vPublisharea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_addtime
     *
     * @return the value of sea_co_data.v_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvAddtime() {
        return vAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_addtime
     *
     * @param vAddtime the value for sea_co_data.v_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvAddtime(Integer vAddtime) {
        this.vAddtime = vAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_topic
     *
     * @return the value of sea_co_data.v_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvTopic() {
        return vTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_topic
     *
     * @param vTopic the value for sea_co_data.v_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvTopic(Integer vTopic) {
        this.vTopic = vTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_note
     *
     * @return the value of sea_co_data.v_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvNote() {
        return vNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_note
     *
     * @param vNote the value for sea_co_data.v_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvNote(String vNote) {
        this.vNote = vNote == null ? null : vNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_tags
     *
     * @return the value of sea_co_data.v_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvTags() {
        return vTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_tags
     *
     * @param vTags the value for sea_co_data.v_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvTags(String vTags) {
        this.vTags = vTags == null ? null : vTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_letter
     *
     * @return the value of sea_co_data.v_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvLetter() {
        return vLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_letter
     *
     * @param vLetter the value for sea_co_data.v_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvLetter(String vLetter) {
        this.vLetter = vLetter == null ? null : vLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_from
     *
     * @return the value of sea_co_data.v_from
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvFrom() {
        return vFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_from
     *
     * @param vFrom the value for sea_co_data.v_from
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvFrom(String vFrom) {
        this.vFrom = vFrom == null ? null : vFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_data.v_inbase
     *
     * @return the value of sea_co_data.v_inbase
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvInbase() {
        return vInbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_data.v_inbase
     *
     * @param vInbase the value for sea_co_data.v_inbase
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvInbase(String vInbase) {
        this.vInbase = vInbase == null ? null : vInbase.trim();
    }
}