package com.pipimovie.dataobject;

public class CofiltersDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_filters.ID
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_filters.Name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_filters.rColumn
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Boolean rcolumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_filters.uesMode
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Boolean uesmode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_filters.sFind
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String sfind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_filters.sStart
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String sstart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_filters.sEnd
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String send;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_filters.sReplace
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String sreplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_filters.Flag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Boolean flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_filters.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Byte cotype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_filters
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CofiltersDO(Integer id, String name, Boolean rcolumn, Boolean uesmode, String sfind, String sstart, String send, String sreplace, Boolean flag, Byte cotype) {
        this.id = id;
        this.name = name;
        this.rcolumn = rcolumn;
        this.uesmode = uesmode;
        this.sfind = sfind;
        this.sstart = sstart;
        this.send = send;
        this.sreplace = sreplace;
        this.flag = flag;
        this.cotype = cotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_filters
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CofiltersDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_filters.ID
     *
     * @return the value of sea_co_filters.ID
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_filters.ID
     *
     * @param id the value for sea_co_filters.ID
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_filters.Name
     *
     * @return the value of sea_co_filters.Name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_filters.Name
     *
     * @param name the value for sea_co_filters.Name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_filters.rColumn
     *
     * @return the value of sea_co_filters.rColumn
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Boolean getRcolumn() {
        return rcolumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_filters.rColumn
     *
     * @param rcolumn the value for sea_co_filters.rColumn
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setRcolumn(Boolean rcolumn) {
        this.rcolumn = rcolumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_filters.uesMode
     *
     * @return the value of sea_co_filters.uesMode
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Boolean getUesmode() {
        return uesmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_filters.uesMode
     *
     * @param uesmode the value for sea_co_filters.uesMode
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setUesmode(Boolean uesmode) {
        this.uesmode = uesmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_filters.sFind
     *
     * @return the value of sea_co_filters.sFind
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getSfind() {
        return sfind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_filters.sFind
     *
     * @param sfind the value for sea_co_filters.sFind
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setSfind(String sfind) {
        this.sfind = sfind == null ? null : sfind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_filters.sStart
     *
     * @return the value of sea_co_filters.sStart
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getSstart() {
        return sstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_filters.sStart
     *
     * @param sstart the value for sea_co_filters.sStart
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setSstart(String sstart) {
        this.sstart = sstart == null ? null : sstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_filters.sEnd
     *
     * @return the value of sea_co_filters.sEnd
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getSend() {
        return send;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_filters.sEnd
     *
     * @param send the value for sea_co_filters.sEnd
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setSend(String send) {
        this.send = send == null ? null : send.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_filters.sReplace
     *
     * @return the value of sea_co_filters.sReplace
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getSreplace() {
        return sreplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_filters.sReplace
     *
     * @param sreplace the value for sea_co_filters.sReplace
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setSreplace(String sreplace) {
        this.sreplace = sreplace == null ? null : sreplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_filters.Flag
     *
     * @return the value of sea_co_filters.Flag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_filters.Flag
     *
     * @param flag the value for sea_co_filters.Flag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_filters.cotype
     *
     * @return the value of sea_co_filters.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Byte getCotype() {
        return cotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_filters.cotype
     *
     * @param cotype the value for sea_co_filters.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCotype(Byte cotype) {
        this.cotype = cotype;
    }
}