package com.pipimovie.dataobject;

public class CommentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.uid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.typeid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.username
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.ip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.ischeck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short ischeck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.dtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer dtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.msg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.m_type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer mType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.reply
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer reply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.agree
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer agree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.anti
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer anti;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_comment.vote
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vote;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_comment
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CommentDO(Integer id, Integer uid, Integer vId, Short typeid, String username, String ip, Short ischeck, Integer dtime, String msg, Integer mType, Integer reply, Integer agree, Integer anti, String pic, Integer vote) {
        this.id = id;
        this.uid = uid;
        this.vId = vId;
        this.typeid = typeid;
        this.username = username;
        this.ip = ip;
        this.ischeck = ischeck;
        this.dtime = dtime;
        this.msg = msg;
        this.mType = mType;
        this.reply = reply;
        this.agree = agree;
        this.anti = anti;
        this.pic = pic;
        this.vote = vote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_comment
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CommentDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.id
     *
     * @return the value of sea_comment.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.id
     *
     * @param id the value for sea_comment.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.uid
     *
     * @return the value of sea_comment.uid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.uid
     *
     * @param uid the value for sea_comment.uid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.v_id
     *
     * @return the value of sea_comment.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.v_id
     *
     * @param vId the value for sea_comment.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvId(Integer vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.typeid
     *
     * @return the value of sea_comment.typeid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.typeid
     *
     * @param typeid the value for sea_comment.typeid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTypeid(Short typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.username
     *
     * @return the value of sea_comment.username
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.username
     *
     * @param username the value for sea_comment.username
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.ip
     *
     * @return the value of sea_comment.ip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.ip
     *
     * @param ip the value for sea_comment.ip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.ischeck
     *
     * @return the value of sea_comment.ischeck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.ischeck
     *
     * @param ischeck the value for sea_comment.ischeck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setIscheck(Short ischeck) {
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.dtime
     *
     * @return the value of sea_comment.dtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.dtime
     *
     * @param dtime the value for sea_comment.dtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setDtime(Integer dtime) {
        this.dtime = dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.msg
     *
     * @return the value of sea_comment.msg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.msg
     *
     * @param msg the value for sea_comment.msg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.m_type
     *
     * @return the value of sea_comment.m_type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getmType() {
        return mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.m_type
     *
     * @param mType the value for sea_comment.m_type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setmType(Integer mType) {
        this.mType = mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.reply
     *
     * @return the value of sea_comment.reply
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.reply
     *
     * @param reply the value for sea_comment.reply
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setReply(Integer reply) {
        this.reply = reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.agree
     *
     * @return the value of sea_comment.agree
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getAgree() {
        return agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.agree
     *
     * @param agree the value for sea_comment.agree
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAgree(Integer agree) {
        this.agree = agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.anti
     *
     * @return the value of sea_comment.anti
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getAnti() {
        return anti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.anti
     *
     * @param anti the value for sea_comment.anti
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAnti(Integer anti) {
        this.anti = anti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.pic
     *
     * @return the value of sea_comment.pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.pic
     *
     * @param pic the value for sea_comment.pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_comment.vote
     *
     * @return the value of sea_comment.vote
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getVote() {
        return vote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_comment.vote
     *
     * @param vote the value for sea_comment.vote
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setVote(Integer vote) {
        this.vote = vote;
    }
}