package com.pipimovie.dataobject;

public class ConewsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_title
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_keyword
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nKeyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer nHit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_author
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer nAddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_outline
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nOutline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_from
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_inbase
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nInbase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_news.n_entitle
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nEntitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_news
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public ConewsDO(Integer nId, Short tid, String nTitle, String nKeyword, String nPic, Integer nHit, String nAuthor, Integer nAddtime, String nLetter, String nContent, String nOutline, String tname, String nFrom, String nInbase, String nEntitle) {
        this.nId = nId;
        this.tid = tid;
        this.nTitle = nTitle;
        this.nKeyword = nKeyword;
        this.nPic = nPic;
        this.nHit = nHit;
        this.nAuthor = nAuthor;
        this.nAddtime = nAddtime;
        this.nLetter = nLetter;
        this.nContent = nContent;
        this.nOutline = nOutline;
        this.tname = tname;
        this.nFrom = nFrom;
        this.nInbase = nInbase;
        this.nEntitle = nEntitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_news
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public ConewsDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_id
     *
     * @return the value of sea_co_news.n_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_id
     *
     * @param nId the value for sea_co_news.n_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnId(Integer nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.tid
     *
     * @return the value of sea_co_news.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.tid
     *
     * @param tid the value for sea_co_news.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTid(Short tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_title
     *
     * @return the value of sea_co_news.n_title
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnTitle() {
        return nTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_title
     *
     * @param nTitle the value for sea_co_news.n_title
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnTitle(String nTitle) {
        this.nTitle = nTitle == null ? null : nTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_keyword
     *
     * @return the value of sea_co_news.n_keyword
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnKeyword() {
        return nKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_keyword
     *
     * @param nKeyword the value for sea_co_news.n_keyword
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnKeyword(String nKeyword) {
        this.nKeyword = nKeyword == null ? null : nKeyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_pic
     *
     * @return the value of sea_co_news.n_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnPic() {
        return nPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_pic
     *
     * @param nPic the value for sea_co_news.n_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnPic(String nPic) {
        this.nPic = nPic == null ? null : nPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_hit
     *
     * @return the value of sea_co_news.n_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getnHit() {
        return nHit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_hit
     *
     * @param nHit the value for sea_co_news.n_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnHit(Integer nHit) {
        this.nHit = nHit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_author
     *
     * @return the value of sea_co_news.n_author
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnAuthor() {
        return nAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_author
     *
     * @param nAuthor the value for sea_co_news.n_author
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnAuthor(String nAuthor) {
        this.nAuthor = nAuthor == null ? null : nAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_addtime
     *
     * @return the value of sea_co_news.n_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getnAddtime() {
        return nAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_addtime
     *
     * @param nAddtime the value for sea_co_news.n_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnAddtime(Integer nAddtime) {
        this.nAddtime = nAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_letter
     *
     * @return the value of sea_co_news.n_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnLetter() {
        return nLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_letter
     *
     * @param nLetter the value for sea_co_news.n_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnLetter(String nLetter) {
        this.nLetter = nLetter == null ? null : nLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_content
     *
     * @return the value of sea_co_news.n_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnContent() {
        return nContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_content
     *
     * @param nContent the value for sea_co_news.n_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnContent(String nContent) {
        this.nContent = nContent == null ? null : nContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_outline
     *
     * @return the value of sea_co_news.n_outline
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnOutline() {
        return nOutline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_outline
     *
     * @param nOutline the value for sea_co_news.n_outline
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnOutline(String nOutline) {
        this.nOutline = nOutline == null ? null : nOutline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.tname
     *
     * @return the value of sea_co_news.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.tname
     *
     * @param tname the value for sea_co_news.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_from
     *
     * @return the value of sea_co_news.n_from
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnFrom() {
        return nFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_from
     *
     * @param nFrom the value for sea_co_news.n_from
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnFrom(String nFrom) {
        this.nFrom = nFrom == null ? null : nFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_inbase
     *
     * @return the value of sea_co_news.n_inbase
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnInbase() {
        return nInbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_inbase
     *
     * @param nInbase the value for sea_co_news.n_inbase
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnInbase(String nInbase) {
        this.nInbase = nInbase == null ? null : nInbase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_news.n_entitle
     *
     * @return the value of sea_co_news.n_entitle
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnEntitle() {
        return nEntitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_news.n_entitle
     *
     * @param nEntitle the value for sea_co_news.n_entitle
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnEntitle(String nEntitle) {
        this.nEntitle = nEntitle == null ? null : nEntitle.trim();
    }
}