package com.pipimovie.dataobject;

public class CotypeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.cid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.siteurl
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String siteurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.getherday
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short getherday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.playfrom
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String playfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.autocls
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String autocls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.classid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.coding
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String coding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.sock
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String sock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.cjtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer cjtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.listconfig
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String listconfig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.itemconfig
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String itemconfig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.isok
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Boolean isok;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_co_type.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Byte cotype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CotypeDO(Integer tid, Short cid, String tname, String siteurl, Short getherday, String playfrom, String autocls, Short classid, String coding, String sock, Integer addtime, Integer cjtime, String listconfig, String itemconfig, Boolean isok, Byte cotype) {
        this.tid = tid;
        this.cid = cid;
        this.tname = tname;
        this.siteurl = siteurl;
        this.getherday = getherday;
        this.playfrom = playfrom;
        this.autocls = autocls;
        this.classid = classid;
        this.coding = coding;
        this.sock = sock;
        this.addtime = addtime;
        this.cjtime = cjtime;
        this.listconfig = listconfig;
        this.itemconfig = itemconfig;
        this.isok = isok;
        this.cotype = cotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CotypeDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.tid
     *
     * @return the value of sea_co_type.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.tid
     *
     * @param tid the value for sea_co_type.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.cid
     *
     * @return the value of sea_co_type.cid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.cid
     *
     * @param cid the value for sea_co_type.cid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCid(Short cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.tname
     *
     * @return the value of sea_co_type.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.tname
     *
     * @param tname the value for sea_co_type.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.siteurl
     *
     * @return the value of sea_co_type.siteurl
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getSiteurl() {
        return siteurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.siteurl
     *
     * @param siteurl the value for sea_co_type.siteurl
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setSiteurl(String siteurl) {
        this.siteurl = siteurl == null ? null : siteurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.getherday
     *
     * @return the value of sea_co_type.getherday
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getGetherday() {
        return getherday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.getherday
     *
     * @param getherday the value for sea_co_type.getherday
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setGetherday(Short getherday) {
        this.getherday = getherday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.playfrom
     *
     * @return the value of sea_co_type.playfrom
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getPlayfrom() {
        return playfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.playfrom
     *
     * @param playfrom the value for sea_co_type.playfrom
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setPlayfrom(String playfrom) {
        this.playfrom = playfrom == null ? null : playfrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.autocls
     *
     * @return the value of sea_co_type.autocls
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getAutocls() {
        return autocls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.autocls
     *
     * @param autocls the value for sea_co_type.autocls
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAutocls(String autocls) {
        this.autocls = autocls == null ? null : autocls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.classid
     *
     * @return the value of sea_co_type.classid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.classid
     *
     * @param classid the value for sea_co_type.classid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setClassid(Short classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.coding
     *
     * @return the value of sea_co_type.coding
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getCoding() {
        return coding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.coding
     *
     * @param coding the value for sea_co_type.coding
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCoding(String coding) {
        this.coding = coding == null ? null : coding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.sock
     *
     * @return the value of sea_co_type.sock
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getSock() {
        return sock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.sock
     *
     * @param sock the value for sea_co_type.sock
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setSock(String sock) {
        this.sock = sock == null ? null : sock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.addtime
     *
     * @return the value of sea_co_type.addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.addtime
     *
     * @param addtime the value for sea_co_type.addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.cjtime
     *
     * @return the value of sea_co_type.cjtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getCjtime() {
        return cjtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.cjtime
     *
     * @param cjtime the value for sea_co_type.cjtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCjtime(Integer cjtime) {
        this.cjtime = cjtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.listconfig
     *
     * @return the value of sea_co_type.listconfig
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getListconfig() {
        return listconfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.listconfig
     *
     * @param listconfig the value for sea_co_type.listconfig
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setListconfig(String listconfig) {
        this.listconfig = listconfig == null ? null : listconfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.itemconfig
     *
     * @return the value of sea_co_type.itemconfig
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getItemconfig() {
        return itemconfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.itemconfig
     *
     * @param itemconfig the value for sea_co_type.itemconfig
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setItemconfig(String itemconfig) {
        this.itemconfig = itemconfig == null ? null : itemconfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.isok
     *
     * @return the value of sea_co_type.isok
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Boolean getIsok() {
        return isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.isok
     *
     * @param isok the value for sea_co_type.isok
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setIsok(Boolean isok) {
        this.isok = isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_co_type.cotype
     *
     * @return the value of sea_co_type.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Byte getCotype() {
        return cotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_co_type.cotype
     *
     * @param cotype the value for sea_co_type.cotype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCotype(Byte cotype) {
        this.cotype = cotype;
    }
}