package com.pipimovie.dataobject;

public class CountDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_count.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_count.userip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String userip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_count.serverurl
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String serverurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_count.updatetime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_count
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CountDO(Integer id, String userip, String serverurl, String updatetime) {
        this.id = id;
        this.userip = userip;
        this.serverurl = serverurl;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_count
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CountDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_count.id
     *
     * @return the value of sea_count.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_count.id
     *
     * @param id the value for sea_count.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_count.userip
     *
     * @return the value of sea_count.userip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getUserip() {
        return userip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_count.userip
     *
     * @param userip the value for sea_count.userip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setUserip(String userip) {
        this.userip = userip == null ? null : userip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_count.serverurl
     *
     * @return the value of sea_count.serverurl
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getServerurl() {
        return serverurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_count.serverurl
     *
     * @param serverurl the value for sea_count.serverurl
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setServerurl(String serverurl) {
        this.serverurl = serverurl == null ? null : serverurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_count.updatetime
     *
     * @return the value of sea_count.updatetime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_count.updatetime
     *
     * @param updatetime the value for sea_count.updatetime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}