package com.pipimovie.dataobject;

public class CronsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_crons.cronid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short cronid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_crons.available
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Boolean available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_crons.type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_crons.name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_crons.filename
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_crons.lastrun
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer lastrun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_crons.nextrun
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer nextrun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_crons.weekday
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Boolean weekday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_crons.day
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Byte day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_crons.hour
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Byte hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_crons.minute
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String minute;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_crons
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CronsDO(Short cronid, Boolean available, String type, String name, String filename, Integer lastrun, Integer nextrun, Boolean weekday, Byte day, Byte hour, String minute) {
        this.cronid = cronid;
        this.available = available;
        this.type = type;
        this.name = name;
        this.filename = filename;
        this.lastrun = lastrun;
        this.nextrun = nextrun;
        this.weekday = weekday;
        this.day = day;
        this.hour = hour;
        this.minute = minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_crons
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public CronsDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_crons.cronid
     *
     * @return the value of sea_crons.cronid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getCronid() {
        return cronid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_crons.cronid
     *
     * @param cronid the value for sea_crons.cronid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCronid(Short cronid) {
        this.cronid = cronid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_crons.available
     *
     * @return the value of sea_crons.available
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_crons.available
     *
     * @param available the value for sea_crons.available
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_crons.type
     *
     * @return the value of sea_crons.type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_crons.type
     *
     * @param type the value for sea_crons.type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_crons.name
     *
     * @return the value of sea_crons.name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_crons.name
     *
     * @param name the value for sea_crons.name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_crons.filename
     *
     * @return the value of sea_crons.filename
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_crons.filename
     *
     * @param filename the value for sea_crons.filename
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_crons.lastrun
     *
     * @return the value of sea_crons.lastrun
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getLastrun() {
        return lastrun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_crons.lastrun
     *
     * @param lastrun the value for sea_crons.lastrun
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setLastrun(Integer lastrun) {
        this.lastrun = lastrun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_crons.nextrun
     *
     * @return the value of sea_crons.nextrun
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getNextrun() {
        return nextrun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_crons.nextrun
     *
     * @param nextrun the value for sea_crons.nextrun
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setNextrun(Integer nextrun) {
        this.nextrun = nextrun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_crons.weekday
     *
     * @return the value of sea_crons.weekday
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Boolean getWeekday() {
        return weekday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_crons.weekday
     *
     * @param weekday the value for sea_crons.weekday
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setWeekday(Boolean weekday) {
        this.weekday = weekday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_crons.day
     *
     * @return the value of sea_crons.day
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Byte getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_crons.day
     *
     * @param day the value for sea_crons.day
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setDay(Byte day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_crons.hour
     *
     * @return the value of sea_crons.hour
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Byte getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_crons.hour
     *
     * @param hour the value for sea_crons.hour
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setHour(Byte hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_crons.minute
     *
     * @return the value of sea_crons.minute
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getMinute() {
        return minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_crons.minute
     *
     * @param minute the value for sea_crons.minute
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setMinute(String minute) {
        this.minute = minute == null ? null : minute.trim();
    }
}