package com.pipimovie.dataobject;

public class DataDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_spic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vSpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_gpic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vGpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vHit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_money
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_rank
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_digg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vDigg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_tread
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vTread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_commend
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vCommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_wrong
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vWrong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_ismake
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vIsmake;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_actor
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vActor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_color
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_publishyear
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vPublishyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_publisharea
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vPublisharea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vAddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vTags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_isunion
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vIsunion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_recycled
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short vRecycled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_director
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vDirector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_enname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vEnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_lang
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vLang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_score
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_scorenum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vScorenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_extratype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vExtratype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_jq
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vJq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_nickname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_reweek
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vReweek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_douban
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Float vDouban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_mtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Float vMtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_imdb
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Float vImdb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_tvs
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vTvs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_company
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_dayhit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vDayhit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_weekhit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vWeekhit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_monthhit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vMonthhit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_daytime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vDaytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_weektime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vWeektime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_monthtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vMonthtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_len
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vLen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_total
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_ver
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vVer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_psd
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_longtxt
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vLongtxt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_data
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public DataDO(Integer vId, Short tid, String vName, Integer vState, String vPic, String vSpic, String vGpic, Integer vHit, Short vMoney, Short vRank, Short vDigg, Short vTread, Short vCommend, Short vWrong, Short vIsmake, String vActor, String vColor, Integer vPublishyear, String vPublisharea, Integer vAddtime, Integer vTopic, String vNote, String vTags, String vLetter, Short vIsunion, Short vRecycled, String vDirector, String vEnname, String vLang, Integer vScore, Integer vScorenum, String vExtratype, String vJq, String vNickname, String vReweek, Float vDouban, Float vMtime, Float vImdb, String vTvs, String vCompany, Integer vDayhit, Integer vWeekhit, Integer vMonthhit, Integer vDaytime, Integer vWeektime, Integer vMonthtime, String vLen, String vTotal, String vVer, String vPsd, String vLongtxt) {
        this.vId = vId;
        this.tid = tid;
        this.vName = vName;
        this.vState = vState;
        this.vPic = vPic;
        this.vSpic = vSpic;
        this.vGpic = vGpic;
        this.vHit = vHit;
        this.vMoney = vMoney;
        this.vRank = vRank;
        this.vDigg = vDigg;
        this.vTread = vTread;
        this.vCommend = vCommend;
        this.vWrong = vWrong;
        this.vIsmake = vIsmake;
        this.vActor = vActor;
        this.vColor = vColor;
        this.vPublishyear = vPublishyear;
        this.vPublisharea = vPublisharea;
        this.vAddtime = vAddtime;
        this.vTopic = vTopic;
        this.vNote = vNote;
        this.vTags = vTags;
        this.vLetter = vLetter;
        this.vIsunion = vIsunion;
        this.vRecycled = vRecycled;
        this.vDirector = vDirector;
        this.vEnname = vEnname;
        this.vLang = vLang;
        this.vScore = vScore;
        this.vScorenum = vScorenum;
        this.vExtratype = vExtratype;
        this.vJq = vJq;
        this.vNickname = vNickname;
        this.vReweek = vReweek;
        this.vDouban = vDouban;
        this.vMtime = vMtime;
        this.vImdb = vImdb;
        this.vTvs = vTvs;
        this.vCompany = vCompany;
        this.vDayhit = vDayhit;
        this.vWeekhit = vWeekhit;
        this.vMonthhit = vMonthhit;
        this.vDaytime = vDaytime;
        this.vWeektime = vWeektime;
        this.vMonthtime = vMonthtime;
        this.vLen = vLen;
        this.vTotal = vTotal;
        this.vVer = vVer;
        this.vPsd = vPsd;
        this.vLongtxt = vLongtxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_data
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public DataDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_id
     *
     * @return the value of sea_data.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_id
     *
     * @param vId the value for sea_data.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvId(Integer vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.tid
     *
     * @return the value of sea_data.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.tid
     *
     * @param tid the value for sea_data.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTid(Short tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_name
     *
     * @return the value of sea_data.v_name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvName() {
        return vName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_name
     *
     * @param vName the value for sea_data.v_name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvName(String vName) {
        this.vName = vName == null ? null : vName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_state
     *
     * @return the value of sea_data.v_state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvState() {
        return vState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_state
     *
     * @param vState the value for sea_data.v_state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvState(Integer vState) {
        this.vState = vState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_pic
     *
     * @return the value of sea_data.v_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvPic() {
        return vPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_pic
     *
     * @param vPic the value for sea_data.v_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvPic(String vPic) {
        this.vPic = vPic == null ? null : vPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_spic
     *
     * @return the value of sea_data.v_spic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvSpic() {
        return vSpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_spic
     *
     * @param vSpic the value for sea_data.v_spic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvSpic(String vSpic) {
        this.vSpic = vSpic == null ? null : vSpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_gpic
     *
     * @return the value of sea_data.v_gpic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvGpic() {
        return vGpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_gpic
     *
     * @param vGpic the value for sea_data.v_gpic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvGpic(String vGpic) {
        this.vGpic = vGpic == null ? null : vGpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_hit
     *
     * @return the value of sea_data.v_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvHit() {
        return vHit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_hit
     *
     * @param vHit the value for sea_data.v_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvHit(Integer vHit) {
        this.vHit = vHit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_money
     *
     * @return the value of sea_data.v_money
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvMoney() {
        return vMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_money
     *
     * @param vMoney the value for sea_data.v_money
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvMoney(Short vMoney) {
        this.vMoney = vMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_rank
     *
     * @return the value of sea_data.v_rank
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvRank() {
        return vRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_rank
     *
     * @param vRank the value for sea_data.v_rank
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvRank(Short vRank) {
        this.vRank = vRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_digg
     *
     * @return the value of sea_data.v_digg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvDigg() {
        return vDigg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_digg
     *
     * @param vDigg the value for sea_data.v_digg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvDigg(Short vDigg) {
        this.vDigg = vDigg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_tread
     *
     * @return the value of sea_data.v_tread
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvTread() {
        return vTread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_tread
     *
     * @param vTread the value for sea_data.v_tread
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvTread(Short vTread) {
        this.vTread = vTread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_commend
     *
     * @return the value of sea_data.v_commend
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvCommend() {
        return vCommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_commend
     *
     * @param vCommend the value for sea_data.v_commend
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvCommend(Short vCommend) {
        this.vCommend = vCommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_wrong
     *
     * @return the value of sea_data.v_wrong
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvWrong() {
        return vWrong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_wrong
     *
     * @param vWrong the value for sea_data.v_wrong
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvWrong(Short vWrong) {
        this.vWrong = vWrong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_ismake
     *
     * @return the value of sea_data.v_ismake
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvIsmake() {
        return vIsmake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_ismake
     *
     * @param vIsmake the value for sea_data.v_ismake
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvIsmake(Short vIsmake) {
        this.vIsmake = vIsmake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_actor
     *
     * @return the value of sea_data.v_actor
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvActor() {
        return vActor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_actor
     *
     * @param vActor the value for sea_data.v_actor
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvActor(String vActor) {
        this.vActor = vActor == null ? null : vActor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_color
     *
     * @return the value of sea_data.v_color
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvColor() {
        return vColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_color
     *
     * @param vColor the value for sea_data.v_color
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvColor(String vColor) {
        this.vColor = vColor == null ? null : vColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_publishyear
     *
     * @return the value of sea_data.v_publishyear
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvPublishyear() {
        return vPublishyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_publishyear
     *
     * @param vPublishyear the value for sea_data.v_publishyear
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvPublishyear(Integer vPublishyear) {
        this.vPublishyear = vPublishyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_publisharea
     *
     * @return the value of sea_data.v_publisharea
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvPublisharea() {
        return vPublisharea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_publisharea
     *
     * @param vPublisharea the value for sea_data.v_publisharea
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvPublisharea(String vPublisharea) {
        this.vPublisharea = vPublisharea == null ? null : vPublisharea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_addtime
     *
     * @return the value of sea_data.v_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvAddtime() {
        return vAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_addtime
     *
     * @param vAddtime the value for sea_data.v_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvAddtime(Integer vAddtime) {
        this.vAddtime = vAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_topic
     *
     * @return the value of sea_data.v_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvTopic() {
        return vTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_topic
     *
     * @param vTopic the value for sea_data.v_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvTopic(Integer vTopic) {
        this.vTopic = vTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_note
     *
     * @return the value of sea_data.v_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvNote() {
        return vNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_note
     *
     * @param vNote the value for sea_data.v_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvNote(String vNote) {
        this.vNote = vNote == null ? null : vNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_tags
     *
     * @return the value of sea_data.v_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvTags() {
        return vTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_tags
     *
     * @param vTags the value for sea_data.v_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvTags(String vTags) {
        this.vTags = vTags == null ? null : vTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_letter
     *
     * @return the value of sea_data.v_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvLetter() {
        return vLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_letter
     *
     * @param vLetter the value for sea_data.v_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvLetter(String vLetter) {
        this.vLetter = vLetter == null ? null : vLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_isunion
     *
     * @return the value of sea_data.v_isunion
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvIsunion() {
        return vIsunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_isunion
     *
     * @param vIsunion the value for sea_data.v_isunion
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvIsunion(Short vIsunion) {
        this.vIsunion = vIsunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_recycled
     *
     * @return the value of sea_data.v_recycled
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getvRecycled() {
        return vRecycled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_recycled
     *
     * @param vRecycled the value for sea_data.v_recycled
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvRecycled(Short vRecycled) {
        this.vRecycled = vRecycled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_director
     *
     * @return the value of sea_data.v_director
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvDirector() {
        return vDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_director
     *
     * @param vDirector the value for sea_data.v_director
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvDirector(String vDirector) {
        this.vDirector = vDirector == null ? null : vDirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_enname
     *
     * @return the value of sea_data.v_enname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvEnname() {
        return vEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_enname
     *
     * @param vEnname the value for sea_data.v_enname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvEnname(String vEnname) {
        this.vEnname = vEnname == null ? null : vEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_lang
     *
     * @return the value of sea_data.v_lang
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvLang() {
        return vLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_lang
     *
     * @param vLang the value for sea_data.v_lang
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvLang(String vLang) {
        this.vLang = vLang == null ? null : vLang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_score
     *
     * @return the value of sea_data.v_score
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvScore() {
        return vScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_score
     *
     * @param vScore the value for sea_data.v_score
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvScore(Integer vScore) {
        this.vScore = vScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_scorenum
     *
     * @return the value of sea_data.v_scorenum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvScorenum() {
        return vScorenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_scorenum
     *
     * @param vScorenum the value for sea_data.v_scorenum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvScorenum(Integer vScorenum) {
        this.vScorenum = vScorenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_extratype
     *
     * @return the value of sea_data.v_extratype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvExtratype() {
        return vExtratype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_extratype
     *
     * @param vExtratype the value for sea_data.v_extratype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvExtratype(String vExtratype) {
        this.vExtratype = vExtratype == null ? null : vExtratype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_jq
     *
     * @return the value of sea_data.v_jq
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvJq() {
        return vJq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_jq
     *
     * @param vJq the value for sea_data.v_jq
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvJq(String vJq) {
        this.vJq = vJq == null ? null : vJq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_nickname
     *
     * @return the value of sea_data.v_nickname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvNickname() {
        return vNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_nickname
     *
     * @param vNickname the value for sea_data.v_nickname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvNickname(String vNickname) {
        this.vNickname = vNickname == null ? null : vNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_reweek
     *
     * @return the value of sea_data.v_reweek
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvReweek() {
        return vReweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_reweek
     *
     * @param vReweek the value for sea_data.v_reweek
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvReweek(String vReweek) {
        this.vReweek = vReweek == null ? null : vReweek.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_douban
     *
     * @return the value of sea_data.v_douban
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Float getvDouban() {
        return vDouban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_douban
     *
     * @param vDouban the value for sea_data.v_douban
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvDouban(Float vDouban) {
        this.vDouban = vDouban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_mtime
     *
     * @return the value of sea_data.v_mtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Float getvMtime() {
        return vMtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_mtime
     *
     * @param vMtime the value for sea_data.v_mtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvMtime(Float vMtime) {
        this.vMtime = vMtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_imdb
     *
     * @return the value of sea_data.v_imdb
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Float getvImdb() {
        return vImdb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_imdb
     *
     * @param vImdb the value for sea_data.v_imdb
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvImdb(Float vImdb) {
        this.vImdb = vImdb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_tvs
     *
     * @return the value of sea_data.v_tvs
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvTvs() {
        return vTvs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_tvs
     *
     * @param vTvs the value for sea_data.v_tvs
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvTvs(String vTvs) {
        this.vTvs = vTvs == null ? null : vTvs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_company
     *
     * @return the value of sea_data.v_company
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvCompany() {
        return vCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_company
     *
     * @param vCompany the value for sea_data.v_company
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvCompany(String vCompany) {
        this.vCompany = vCompany == null ? null : vCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_dayhit
     *
     * @return the value of sea_data.v_dayhit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvDayhit() {
        return vDayhit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_dayhit
     *
     * @param vDayhit the value for sea_data.v_dayhit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvDayhit(Integer vDayhit) {
        this.vDayhit = vDayhit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_weekhit
     *
     * @return the value of sea_data.v_weekhit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvWeekhit() {
        return vWeekhit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_weekhit
     *
     * @param vWeekhit the value for sea_data.v_weekhit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvWeekhit(Integer vWeekhit) {
        this.vWeekhit = vWeekhit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_monthhit
     *
     * @return the value of sea_data.v_monthhit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvMonthhit() {
        return vMonthhit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_monthhit
     *
     * @param vMonthhit the value for sea_data.v_monthhit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvMonthhit(Integer vMonthhit) {
        this.vMonthhit = vMonthhit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_daytime
     *
     * @return the value of sea_data.v_daytime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvDaytime() {
        return vDaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_daytime
     *
     * @param vDaytime the value for sea_data.v_daytime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvDaytime(Integer vDaytime) {
        this.vDaytime = vDaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_weektime
     *
     * @return the value of sea_data.v_weektime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvWeektime() {
        return vWeektime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_weektime
     *
     * @param vWeektime the value for sea_data.v_weektime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvWeektime(Integer vWeektime) {
        this.vWeektime = vWeektime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_monthtime
     *
     * @return the value of sea_data.v_monthtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvMonthtime() {
        return vMonthtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_monthtime
     *
     * @param vMonthtime the value for sea_data.v_monthtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvMonthtime(Integer vMonthtime) {
        this.vMonthtime = vMonthtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_len
     *
     * @return the value of sea_data.v_len
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvLen() {
        return vLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_len
     *
     * @param vLen the value for sea_data.v_len
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvLen(String vLen) {
        this.vLen = vLen == null ? null : vLen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_total
     *
     * @return the value of sea_data.v_total
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvTotal() {
        return vTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_total
     *
     * @param vTotal the value for sea_data.v_total
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvTotal(String vTotal) {
        this.vTotal = vTotal == null ? null : vTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_ver
     *
     * @return the value of sea_data.v_ver
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvVer() {
        return vVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_ver
     *
     * @param vVer the value for sea_data.v_ver
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvVer(String vVer) {
        this.vVer = vVer == null ? null : vVer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_psd
     *
     * @return the value of sea_data.v_psd
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvPsd() {
        return vPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_psd
     *
     * @param vPsd the value for sea_data.v_psd
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvPsd(String vPsd) {
        this.vPsd = vPsd == null ? null : vPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_data.v_longtxt
     *
     * @return the value of sea_data.v_longtxt
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvLongtxt() {
        return vLongtxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_data.v_longtxt
     *
     * @param vLongtxt the value for sea_data.v_longtxt
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvLongtxt(String vLongtxt) {
        this.vLongtxt = vLongtxt == null ? null : vLongtxt.trim();
    }
}