package com.pipimovie.dataobject;

public class ErraddDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_erradd.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_erradd.vid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_erradd.author
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_erradd.ip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_erradd.errtxt
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String errtxt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_erradd.sendtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer sendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_erradd.ischeck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer ischeck;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_erradd
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public ErraddDO(Integer id, Integer vid, String author, String ip, String errtxt, Integer sendtime, Integer ischeck) {
        this.id = id;
        this.vid = vid;
        this.author = author;
        this.ip = ip;
        this.errtxt = errtxt;
        this.sendtime = sendtime;
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_erradd
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public ErraddDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_erradd.id
     *
     * @return the value of sea_erradd.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_erradd.id
     *
     * @param id the value for sea_erradd.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_erradd.vid
     *
     * @return the value of sea_erradd.vid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_erradd.vid
     *
     * @param vid the value for sea_erradd.vid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_erradd.author
     *
     * @return the value of sea_erradd.author
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_erradd.author
     *
     * @param author the value for sea_erradd.author
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_erradd.ip
     *
     * @return the value of sea_erradd.ip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_erradd.ip
     *
     * @param ip the value for sea_erradd.ip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_erradd.errtxt
     *
     * @return the value of sea_erradd.errtxt
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getErrtxt() {
        return errtxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_erradd.errtxt
     *
     * @param errtxt the value for sea_erradd.errtxt
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setErrtxt(String errtxt) {
        this.errtxt = errtxt == null ? null : errtxt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_erradd.sendtime
     *
     * @return the value of sea_erradd.sendtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_erradd.sendtime
     *
     * @param sendtime the value for sea_erradd.sendtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setSendtime(Integer sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_erradd.ischeck
     *
     * @return the value of sea_erradd.ischeck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_erradd.ischeck
     *
     * @param ischeck the value for sea_erradd.ischeck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setIscheck(Integer ischeck) {
        this.ischeck = ischeck;
    }
}