package com.pipimovie.dataobject;

public class FavoriteDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_favorite.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_favorite.uid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_favorite.vid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_favorite.kptime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer kptime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_favorite
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public FavoriteDO(Integer id, Integer uid, Integer vid, Integer kptime) {
        this.id = id;
        this.uid = uid;
        this.vid = vid;
        this.kptime = kptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_favorite
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public FavoriteDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_favorite.id
     *
     * @return the value of sea_favorite.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_favorite.id
     *
     * @param id the value for sea_favorite.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_favorite.uid
     *
     * @return the value of sea_favorite.uid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_favorite.uid
     *
     * @param uid the value for sea_favorite.uid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_favorite.vid
     *
     * @return the value of sea_favorite.vid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_favorite.vid
     *
     * @param vid the value for sea_favorite.vid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_favorite.kptime
     *
     * @return the value of sea_favorite.kptime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getKptime() {
        return kptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_favorite.kptime
     *
     * @param kptime the value for sea_favorite.kptime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setKptime(Integer kptime) {
        this.kptime = kptime;
    }
}