package com.pipimovie.dataobject;

public class JqtypeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_jqtype.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_jqtype.upid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_jqtype.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_jqtype.ishidden
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short ishidden;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_jqtype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public JqtypeDO(Short tid, Short upid, String tname, Short ishidden) {
        this.tid = tid;
        this.upid = upid;
        this.tname = tname;
        this.ishidden = ishidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_jqtype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public JqtypeDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_jqtype.tid
     *
     * @return the value of sea_jqtype.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_jqtype.tid
     *
     * @param tid the value for sea_jqtype.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTid(Short tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_jqtype.upid
     *
     * @return the value of sea_jqtype.upid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getUpid() {
        return upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_jqtype.upid
     *
     * @param upid the value for sea_jqtype.upid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setUpid(Short upid) {
        this.upid = upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_jqtype.tname
     *
     * @return the value of sea_jqtype.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_jqtype.tname
     *
     * @param tname the value for sea_jqtype.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_jqtype.ishidden
     *
     * @return the value of sea_jqtype.ishidden
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getIshidden() {
        return ishidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_jqtype.ishidden
     *
     * @param ishidden the value for sea_jqtype.ishidden
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setIshidden(Short ishidden) {
        this.ishidden = ishidden;
    }
}