package com.pipimovie.dataobject;

public class MemberDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.username
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.nickname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.password
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.email
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.logincount
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short logincount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.regip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String regip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.regtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer regtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.gid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.points
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer points;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.stime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer stime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.vipendtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vipendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.acode
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String acode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.repswcode
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String repswcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.msgbody
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String msgbody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member.msgstate
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String msgstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public MemberDO(Integer id, String username, String nickname, String password, String email, Short logincount, String regip, Integer regtime, Short gid, Integer points, Short state, Integer stime, String vipendtime, String acode, String repswcode, String msgbody, String msgstate) {
        this.id = id;
        this.username = username;
        this.nickname = nickname;
        this.password = password;
        this.email = email;
        this.logincount = logincount;
        this.regip = regip;
        this.regtime = regtime;
        this.gid = gid;
        this.points = points;
        this.state = state;
        this.stime = stime;
        this.vipendtime = vipendtime;
        this.acode = acode;
        this.repswcode = repswcode;
        this.msgbody = msgbody;
        this.msgstate = msgstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public MemberDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.id
     *
     * @return the value of sea_member.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.id
     *
     * @param id the value for sea_member.id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.username
     *
     * @return the value of sea_member.username
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.username
     *
     * @param username the value for sea_member.username
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.nickname
     *
     * @return the value of sea_member.nickname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.nickname
     *
     * @param nickname the value for sea_member.nickname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.password
     *
     * @return the value of sea_member.password
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.password
     *
     * @param password the value for sea_member.password
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.email
     *
     * @return the value of sea_member.email
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.email
     *
     * @param email the value for sea_member.email
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.logincount
     *
     * @return the value of sea_member.logincount
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getLogincount() {
        return logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.logincount
     *
     * @param logincount the value for sea_member.logincount
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setLogincount(Short logincount) {
        this.logincount = logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.regip
     *
     * @return the value of sea_member.regip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getRegip() {
        return regip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.regip
     *
     * @param regip the value for sea_member.regip
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setRegip(String regip) {
        this.regip = regip == null ? null : regip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.regtime
     *
     * @return the value of sea_member.regtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.regtime
     *
     * @param regtime the value for sea_member.regtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setRegtime(Integer regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.gid
     *
     * @return the value of sea_member.gid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.gid
     *
     * @param gid the value for sea_member.gid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setGid(Short gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.points
     *
     * @return the value of sea_member.points
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.points
     *
     * @param points the value for sea_member.points
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.state
     *
     * @return the value of sea_member.state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.state
     *
     * @param state the value for sea_member.state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.stime
     *
     * @return the value of sea_member.stime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.stime
     *
     * @param stime the value for sea_member.stime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setStime(Integer stime) {
        this.stime = stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.vipendtime
     *
     * @return the value of sea_member.vipendtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getVipendtime() {
        return vipendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.vipendtime
     *
     * @param vipendtime the value for sea_member.vipendtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setVipendtime(String vipendtime) {
        this.vipendtime = vipendtime == null ? null : vipendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.acode
     *
     * @return the value of sea_member.acode
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getAcode() {
        return acode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.acode
     *
     * @param acode the value for sea_member.acode
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAcode(String acode) {
        this.acode = acode == null ? null : acode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.repswcode
     *
     * @return the value of sea_member.repswcode
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getRepswcode() {
        return repswcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.repswcode
     *
     * @param repswcode the value for sea_member.repswcode
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setRepswcode(String repswcode) {
        this.repswcode = repswcode == null ? null : repswcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.msgbody
     *
     * @return the value of sea_member.msgbody
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getMsgbody() {
        return msgbody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.msgbody
     *
     * @param msgbody the value for sea_member.msgbody
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setMsgbody(String msgbody) {
        this.msgbody = msgbody == null ? null : msgbody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member.msgstate
     *
     * @return the value of sea_member.msgstate
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getMsgstate() {
        return msgstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member.msgstate
     *
     * @param msgstate the value for sea_member.msgstate
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setMsgstate(String msgstate) {
        this.msgstate = msgstate == null ? null : msgstate.trim();
    }
}