package com.pipimovie.dataobject;

public class MemberGroupDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member_group.gid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member_group.gname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member_group.gtype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String gtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member_group.g_auth
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String gAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member_group.g_upgrade
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer gUpgrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_member_group.g_authvalue
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer gAuthvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member_group
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public MemberGroupDO(Integer gid, String gname, String gtype, String gAuth, Integer gUpgrade, Integer gAuthvalue) {
        this.gid = gid;
        this.gname = gname;
        this.gtype = gtype;
        this.gAuth = gAuth;
        this.gUpgrade = gUpgrade;
        this.gAuthvalue = gAuthvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member_group
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public MemberGroupDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member_group.gid
     *
     * @return the value of sea_member_group.gid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member_group.gid
     *
     * @param gid the value for sea_member_group.gid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member_group.gname
     *
     * @return the value of sea_member_group.gname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member_group.gname
     *
     * @param gname the value for sea_member_group.gname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member_group.gtype
     *
     * @return the value of sea_member_group.gtype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getGtype() {
        return gtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member_group.gtype
     *
     * @param gtype the value for sea_member_group.gtype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setGtype(String gtype) {
        this.gtype = gtype == null ? null : gtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member_group.g_auth
     *
     * @return the value of sea_member_group.g_auth
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getgAuth() {
        return gAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member_group.g_auth
     *
     * @param gAuth the value for sea_member_group.g_auth
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setgAuth(String gAuth) {
        this.gAuth = gAuth == null ? null : gAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member_group.g_upgrade
     *
     * @return the value of sea_member_group.g_upgrade
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getgUpgrade() {
        return gUpgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member_group.g_upgrade
     *
     * @param gUpgrade the value for sea_member_group.g_upgrade
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setgUpgrade(Integer gUpgrade) {
        this.gUpgrade = gUpgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_member_group.g_authvalue
     *
     * @return the value of sea_member_group.g_authvalue
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getgAuthvalue() {
        return gAuthvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_member_group.g_authvalue
     *
     * @param gAuthvalue the value for sea_member_group.g_authvalue
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setgAuthvalue(Integer gAuthvalue) {
        this.gAuthvalue = gAuthvalue;
    }
}