package com.pipimovie.dataobject;

public class MyadDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_myad.aid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_myad.adname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String adname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_myad.adenname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String adenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_myad.timeset
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer timeset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_myad.intro
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_myad.adsbody
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String adsbody;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_myad
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public MyadDO(Integer aid, String adname, String adenname, Integer timeset, String intro, String adsbody) {
        this.aid = aid;
        this.adname = adname;
        this.adenname = adenname;
        this.timeset = timeset;
        this.intro = intro;
        this.adsbody = adsbody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_myad
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public MyadDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_myad.aid
     *
     * @return the value of sea_myad.aid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_myad.aid
     *
     * @param aid the value for sea_myad.aid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_myad.adname
     *
     * @return the value of sea_myad.adname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getAdname() {
        return adname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_myad.adname
     *
     * @param adname the value for sea_myad.adname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAdname(String adname) {
        this.adname = adname == null ? null : adname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_myad.adenname
     *
     * @return the value of sea_myad.adenname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getAdenname() {
        return adenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_myad.adenname
     *
     * @param adenname the value for sea_myad.adenname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAdenname(String adenname) {
        this.adenname = adenname == null ? null : adenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_myad.timeset
     *
     * @return the value of sea_myad.timeset
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getTimeset() {
        return timeset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_myad.timeset
     *
     * @param timeset the value for sea_myad.timeset
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTimeset(Integer timeset) {
        this.timeset = timeset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_myad.intro
     *
     * @return the value of sea_myad.intro
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_myad.intro
     *
     * @param intro the value for sea_myad.intro
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_myad.adsbody
     *
     * @return the value of sea_myad.adsbody
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getAdsbody() {
        return adsbody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_myad.adsbody
     *
     * @param adsbody the value for sea_myad.adsbody
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAdsbody(String adsbody) {
        this.adsbody = adsbody == null ? null : adsbody.trim();
    }
}