package com.pipimovie.dataobject;

public class MytagDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_mytag.aid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_mytag.tagname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String tagname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_mytag.tagdes
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String tagdes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_mytag.addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_mytag.tagcontent
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String tagcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_mytag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public MytagDO(Integer aid, String tagname, String tagdes, Integer addtime, String tagcontent) {
        this.aid = aid;
        this.tagname = tagname;
        this.tagdes = tagdes;
        this.addtime = addtime;
        this.tagcontent = tagcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_mytag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public MytagDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_mytag.aid
     *
     * @return the value of sea_mytag.aid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_mytag.aid
     *
     * @param aid the value for sea_mytag.aid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_mytag.tagname
     *
     * @return the value of sea_mytag.tagname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getTagname() {
        return tagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_mytag.tagname
     *
     * @param tagname the value for sea_mytag.tagname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTagname(String tagname) {
        this.tagname = tagname == null ? null : tagname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_mytag.tagdes
     *
     * @return the value of sea_mytag.tagdes
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getTagdes() {
        return tagdes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_mytag.tagdes
     *
     * @param tagdes the value for sea_mytag.tagdes
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTagdes(String tagdes) {
        this.tagdes = tagdes == null ? null : tagdes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_mytag.addtime
     *
     * @return the value of sea_mytag.addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_mytag.addtime
     *
     * @param addtime the value for sea_mytag.addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_mytag.tagcontent
     *
     * @return the value of sea_mytag.tagcontent
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getTagcontent() {
        return tagcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_mytag.tagcontent
     *
     * @param tagcontent the value for sea_mytag.tagcontent
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTagcontent(String tagcontent) {
        this.tagcontent = tagcontent == null ? null : tagcontent.trim();
    }
}