package com.pipimovie.dataobject;

public class NewsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_title
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer nHit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_money
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short nMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_rank
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short nRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_digg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short nDigg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_tread
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short nTread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_commend
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short nCommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_author
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_color
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer nAddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short nNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_isunion
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short nIsunion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_recycled
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short nRecycled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_entitle
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nEntitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_outline
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nOutline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_keyword
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nKeyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_from
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_score
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Long nScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_scorenum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer nScorenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_news.n_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String nContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_news
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public NewsDO(Integer nId, Short tid, String nTitle, String nPic, Integer nHit, Short nMoney, Short nRank, Short nDigg, Short nTread, Short nCommend, String nAuthor, String nColor, Integer nAddtime, Short nNote, String nLetter, Short nIsunion, Short nRecycled, String nEntitle, String nOutline, String nKeyword, String nFrom, Long nScore, Integer nScorenum, String nContent) {
        this.nId = nId;
        this.tid = tid;
        this.nTitle = nTitle;
        this.nPic = nPic;
        this.nHit = nHit;
        this.nMoney = nMoney;
        this.nRank = nRank;
        this.nDigg = nDigg;
        this.nTread = nTread;
        this.nCommend = nCommend;
        this.nAuthor = nAuthor;
        this.nColor = nColor;
        this.nAddtime = nAddtime;
        this.nNote = nNote;
        this.nLetter = nLetter;
        this.nIsunion = nIsunion;
        this.nRecycled = nRecycled;
        this.nEntitle = nEntitle;
        this.nOutline = nOutline;
        this.nKeyword = nKeyword;
        this.nFrom = nFrom;
        this.nScore = nScore;
        this.nScorenum = nScorenum;
        this.nContent = nContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_news
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public NewsDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_id
     *
     * @return the value of sea_news.n_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_id
     *
     * @param nId the value for sea_news.n_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnId(Integer nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.tid
     *
     * @return the value of sea_news.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.tid
     *
     * @param tid the value for sea_news.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTid(Short tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_title
     *
     * @return the value of sea_news.n_title
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnTitle() {
        return nTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_title
     *
     * @param nTitle the value for sea_news.n_title
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnTitle(String nTitle) {
        this.nTitle = nTitle == null ? null : nTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_pic
     *
     * @return the value of sea_news.n_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnPic() {
        return nPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_pic
     *
     * @param nPic the value for sea_news.n_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnPic(String nPic) {
        this.nPic = nPic == null ? null : nPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_hit
     *
     * @return the value of sea_news.n_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getnHit() {
        return nHit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_hit
     *
     * @param nHit the value for sea_news.n_hit
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnHit(Integer nHit) {
        this.nHit = nHit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_money
     *
     * @return the value of sea_news.n_money
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getnMoney() {
        return nMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_money
     *
     * @param nMoney the value for sea_news.n_money
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnMoney(Short nMoney) {
        this.nMoney = nMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_rank
     *
     * @return the value of sea_news.n_rank
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getnRank() {
        return nRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_rank
     *
     * @param nRank the value for sea_news.n_rank
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnRank(Short nRank) {
        this.nRank = nRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_digg
     *
     * @return the value of sea_news.n_digg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getnDigg() {
        return nDigg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_digg
     *
     * @param nDigg the value for sea_news.n_digg
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnDigg(Short nDigg) {
        this.nDigg = nDigg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_tread
     *
     * @return the value of sea_news.n_tread
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getnTread() {
        return nTread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_tread
     *
     * @param nTread the value for sea_news.n_tread
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnTread(Short nTread) {
        this.nTread = nTread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_commend
     *
     * @return the value of sea_news.n_commend
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getnCommend() {
        return nCommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_commend
     *
     * @param nCommend the value for sea_news.n_commend
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnCommend(Short nCommend) {
        this.nCommend = nCommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_author
     *
     * @return the value of sea_news.n_author
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnAuthor() {
        return nAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_author
     *
     * @param nAuthor the value for sea_news.n_author
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnAuthor(String nAuthor) {
        this.nAuthor = nAuthor == null ? null : nAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_color
     *
     * @return the value of sea_news.n_color
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnColor() {
        return nColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_color
     *
     * @param nColor the value for sea_news.n_color
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnColor(String nColor) {
        this.nColor = nColor == null ? null : nColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_addtime
     *
     * @return the value of sea_news.n_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getnAddtime() {
        return nAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_addtime
     *
     * @param nAddtime the value for sea_news.n_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnAddtime(Integer nAddtime) {
        this.nAddtime = nAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_note
     *
     * @return the value of sea_news.n_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getnNote() {
        return nNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_note
     *
     * @param nNote the value for sea_news.n_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnNote(Short nNote) {
        this.nNote = nNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_letter
     *
     * @return the value of sea_news.n_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnLetter() {
        return nLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_letter
     *
     * @param nLetter the value for sea_news.n_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnLetter(String nLetter) {
        this.nLetter = nLetter == null ? null : nLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_isunion
     *
     * @return the value of sea_news.n_isunion
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getnIsunion() {
        return nIsunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_isunion
     *
     * @param nIsunion the value for sea_news.n_isunion
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnIsunion(Short nIsunion) {
        this.nIsunion = nIsunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_recycled
     *
     * @return the value of sea_news.n_recycled
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getnRecycled() {
        return nRecycled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_recycled
     *
     * @param nRecycled the value for sea_news.n_recycled
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnRecycled(Short nRecycled) {
        this.nRecycled = nRecycled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_entitle
     *
     * @return the value of sea_news.n_entitle
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnEntitle() {
        return nEntitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_entitle
     *
     * @param nEntitle the value for sea_news.n_entitle
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnEntitle(String nEntitle) {
        this.nEntitle = nEntitle == null ? null : nEntitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_outline
     *
     * @return the value of sea_news.n_outline
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnOutline() {
        return nOutline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_outline
     *
     * @param nOutline the value for sea_news.n_outline
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnOutline(String nOutline) {
        this.nOutline = nOutline == null ? null : nOutline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_keyword
     *
     * @return the value of sea_news.n_keyword
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnKeyword() {
        return nKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_keyword
     *
     * @param nKeyword the value for sea_news.n_keyword
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnKeyword(String nKeyword) {
        this.nKeyword = nKeyword == null ? null : nKeyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_from
     *
     * @return the value of sea_news.n_from
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnFrom() {
        return nFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_from
     *
     * @param nFrom the value for sea_news.n_from
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnFrom(String nFrom) {
        this.nFrom = nFrom == null ? null : nFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_score
     *
     * @return the value of sea_news.n_score
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Long getnScore() {
        return nScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_score
     *
     * @param nScore the value for sea_news.n_score
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnScore(Long nScore) {
        this.nScore = nScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_scorenum
     *
     * @return the value of sea_news.n_scorenum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getnScorenum() {
        return nScorenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_scorenum
     *
     * @param nScorenum the value for sea_news.n_scorenum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnScorenum(Integer nScorenum) {
        this.nScorenum = nScorenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_news.n_content
     *
     * @return the value of sea_news.n_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getnContent() {
        return nContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_news.n_content
     *
     * @param nContent the value for sea_news.n_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setnContent(String nContent) {
        this.nContent = nContent == null ? null : nContent.trim();
    }
}