package com.pipimovie.dataobject;

public class PlaydataDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_playdata.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_playdata.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_playdata.body
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String body;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_playdata.body1
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String body1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_playdata
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public PlaydataDO(Integer vId, Short tid, String body, String body1) {
        this.vId = vId;
        this.tid = tid;
        this.body = body;
        this.body1 = body1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_playdata
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public PlaydataDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_playdata.v_id
     *
     * @return the value of sea_playdata.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_playdata.v_id
     *
     * @param vId the value for sea_playdata.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvId(Integer vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_playdata.tid
     *
     * @return the value of sea_playdata.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_playdata.tid
     *
     * @param tid the value for sea_playdata.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTid(Short tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_playdata.body
     *
     * @return the value of sea_playdata.body
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_playdata.body
     *
     * @param body the value for sea_playdata.body
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_playdata.body1
     *
     * @return the value of sea_playdata.body1
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getBody1() {
        return body1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_playdata.body1
     *
     * @param body1 the value for sea_playdata.body1
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setBody1(String body1) {
        this.body1 = body1 == null ? null : body1.trim();
    }
}