package com.pipimovie.dataobject;

public class SearchKeywordsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_search_keywords.aid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_search_keywords.keyword
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_search_keywords.spwords
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String spwords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_search_keywords.count
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_search_keywords.result
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_search_keywords.lasttime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer lasttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_search_keywords.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_search_keywords
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public SearchKeywordsDO(Integer aid, String keyword, String spwords, Integer count, Integer result, Integer lasttime, Short tid) {
        this.aid = aid;
        this.keyword = keyword;
        this.spwords = spwords;
        this.count = count;
        this.result = result;
        this.lasttime = lasttime;
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_search_keywords
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public SearchKeywordsDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_search_keywords.aid
     *
     * @return the value of sea_search_keywords.aid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_search_keywords.aid
     *
     * @param aid the value for sea_search_keywords.aid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_search_keywords.keyword
     *
     * @return the value of sea_search_keywords.keyword
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_search_keywords.keyword
     *
     * @param keyword the value for sea_search_keywords.keyword
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_search_keywords.spwords
     *
     * @return the value of sea_search_keywords.spwords
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getSpwords() {
        return spwords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_search_keywords.spwords
     *
     * @param spwords the value for sea_search_keywords.spwords
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setSpwords(String spwords) {
        this.spwords = spwords == null ? null : spwords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_search_keywords.count
     *
     * @return the value of sea_search_keywords.count
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_search_keywords.count
     *
     * @param count the value for sea_search_keywords.count
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_search_keywords.result
     *
     * @return the value of sea_search_keywords.result
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_search_keywords.result
     *
     * @param result the value for sea_search_keywords.result
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_search_keywords.lasttime
     *
     * @return the value of sea_search_keywords.lasttime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getLasttime() {
        return lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_search_keywords.lasttime
     *
     * @param lasttime the value for sea_search_keywords.lasttime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setLasttime(Integer lasttime) {
        this.lasttime = lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_search_keywords.tid
     *
     * @return the value of sea_search_keywords.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_search_keywords.tid
     *
     * @param tid the value for sea_search_keywords.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTid(Short tid) {
        this.tid = tid;
    }
}