package com.pipimovie.dataobject;

public class TagsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_tags.tagid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer tagid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_tags.tag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_tags.usenum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer usenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_tags.vids
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vids;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public TagsDO(Integer tagid, String tag, Integer usenum, String vids) {
        this.tagid = tagid;
        this.tag = tag;
        this.usenum = usenum;
        this.vids = vids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public TagsDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_tags.tagid
     *
     * @return the value of sea_tags.tagid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_tags.tagid
     *
     * @param tagid the value for sea_tags.tagid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_tags.tag
     *
     * @return the value of sea_tags.tag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_tags.tag
     *
     * @param tag the value for sea_tags.tag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_tags.usenum
     *
     * @return the value of sea_tags.usenum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getUsenum() {
        return usenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_tags.usenum
     *
     * @param usenum the value for sea_tags.usenum
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setUsenum(Integer usenum) {
        this.usenum = usenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_tags.vids
     *
     * @return the value of sea_tags.vids
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getVids() {
        return vids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_tags.vids
     *
     * @param vids the value for sea_tags.vids
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setVids(String vids) {
        this.vids = vids == null ? null : vids.trim();
    }
}