package com.pipimovie.dataobject;

public class TempDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_actor
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vActor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_publishyear
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vPublishyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_publisharea
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vPublisharea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer vAddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_playdata
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vPlaydata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_des
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_director
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vDirector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_enname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vEnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_temp.v_lang
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String vLang;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_temp
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public TempDO(Integer vId, Short tid, String vName, Integer vState, String vPic, String vActor, String vPublishyear, String vPublisharea, Integer vAddtime, String vNote, String vLetter, String vPlaydata, String vDes, String vDirector, String vEnname, String vLang) {
        this.vId = vId;
        this.tid = tid;
        this.vName = vName;
        this.vState = vState;
        this.vPic = vPic;
        this.vActor = vActor;
        this.vPublishyear = vPublishyear;
        this.vPublisharea = vPublisharea;
        this.vAddtime = vAddtime;
        this.vNote = vNote;
        this.vLetter = vLetter;
        this.vPlaydata = vPlaydata;
        this.vDes = vDes;
        this.vDirector = vDirector;
        this.vEnname = vEnname;
        this.vLang = vLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_temp
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public TempDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_id
     *
     * @return the value of sea_temp.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_id
     *
     * @param vId the value for sea_temp.v_id
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvId(Integer vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.tid
     *
     * @return the value of sea_temp.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Short getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.tid
     *
     * @param tid the value for sea_temp.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setTid(Short tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_name
     *
     * @return the value of sea_temp.v_name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvName() {
        return vName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_name
     *
     * @param vName the value for sea_temp.v_name
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvName(String vName) {
        this.vName = vName == null ? null : vName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_state
     *
     * @return the value of sea_temp.v_state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvState() {
        return vState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_state
     *
     * @param vState the value for sea_temp.v_state
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvState(Integer vState) {
        this.vState = vState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_pic
     *
     * @return the value of sea_temp.v_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvPic() {
        return vPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_pic
     *
     * @param vPic the value for sea_temp.v_pic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvPic(String vPic) {
        this.vPic = vPic == null ? null : vPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_actor
     *
     * @return the value of sea_temp.v_actor
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvActor() {
        return vActor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_actor
     *
     * @param vActor the value for sea_temp.v_actor
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvActor(String vActor) {
        this.vActor = vActor == null ? null : vActor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_publishyear
     *
     * @return the value of sea_temp.v_publishyear
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvPublishyear() {
        return vPublishyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_publishyear
     *
     * @param vPublishyear the value for sea_temp.v_publishyear
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvPublishyear(String vPublishyear) {
        this.vPublishyear = vPublishyear == null ? null : vPublishyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_publisharea
     *
     * @return the value of sea_temp.v_publisharea
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvPublisharea() {
        return vPublisharea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_publisharea
     *
     * @param vPublisharea the value for sea_temp.v_publisharea
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvPublisharea(String vPublisharea) {
        this.vPublisharea = vPublisharea == null ? null : vPublisharea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_addtime
     *
     * @return the value of sea_temp.v_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public Integer getvAddtime() {
        return vAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_addtime
     *
     * @param vAddtime the value for sea_temp.v_addtime
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvAddtime(Integer vAddtime) {
        this.vAddtime = vAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_note
     *
     * @return the value of sea_temp.v_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvNote() {
        return vNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_note
     *
     * @param vNote the value for sea_temp.v_note
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvNote(String vNote) {
        this.vNote = vNote == null ? null : vNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_letter
     *
     * @return the value of sea_temp.v_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvLetter() {
        return vLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_letter
     *
     * @param vLetter the value for sea_temp.v_letter
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvLetter(String vLetter) {
        this.vLetter = vLetter == null ? null : vLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_playdata
     *
     * @return the value of sea_temp.v_playdata
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvPlaydata() {
        return vPlaydata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_playdata
     *
     * @param vPlaydata the value for sea_temp.v_playdata
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvPlaydata(String vPlaydata) {
        this.vPlaydata = vPlaydata == null ? null : vPlaydata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_des
     *
     * @return the value of sea_temp.v_des
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvDes() {
        return vDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_des
     *
     * @param vDes the value for sea_temp.v_des
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvDes(String vDes) {
        this.vDes = vDes == null ? null : vDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_director
     *
     * @return the value of sea_temp.v_director
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvDirector() {
        return vDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_director
     *
     * @param vDirector the value for sea_temp.v_director
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvDirector(String vDirector) {
        this.vDirector = vDirector == null ? null : vDirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_enname
     *
     * @return the value of sea_temp.v_enname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvEnname() {
        return vEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_enname
     *
     * @param vEnname the value for sea_temp.v_enname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvEnname(String vEnname) {
        this.vEnname = vEnname == null ? null : vEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sea_temp.v_lang
     *
     * @return the value of sea_temp.v_lang
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public String getvLang() {
        return vLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sea_temp.v_lang
     *
     * @param vLang the value for sea_temp.v_lang
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    public void setvLang(String vLang) {
        this.vLang = vLang == null ? null : vLang.trim();
    }
}