package com.pipimovie.service.businessobject;

import java.util.List;

public class ListVideoBo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_id
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.tid
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Short tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_name
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_state
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_pic
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_hit
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vHit;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_rank
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Short vRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_actor
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vActor;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_publishyear
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vPublishyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_publisharea
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vPublisharea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_addtime
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vAddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_topic
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_note
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vNote;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_letter
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vLetter;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_recycled
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Short vRecycled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_director
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vDirector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_enname
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vEnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_lang
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vLang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_score
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_scorenum
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vScorenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_nickname
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_reweek
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vReweek;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_mtime
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Float vMtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_imdb
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Float vImdb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_dayhit
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vDayhit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_weekhit
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vWeekhit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_monthhit
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vMonthhit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_daytime
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vDaytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_weektime
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vWeektime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_monthtime
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private Integer vMonthtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_len
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vLen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_data.v_total
     *
     * @mbg.generated Mon Jun 22 15:33:34 CST 2020
     */
    private String vTotal;

    private String typeName;

    @Override
    public String toString() {
        return "ListVideoBo{" +
                "vId=" + vId +
                ", tid=" + tid +
                ", vName='" + vName + '\'' +
                ", vState=" + vState +
                ", vPic='" + vPic + '\'' +
                ", vHit=" + vHit +
                ", vRank=" + vRank +
                ", vActor='" + vActor + '\'' +
                ", vPublishyear=" + vPublishyear +
                ", vPublisharea='" + vPublisharea + '\'' +
                ", vAddtime=" + vAddtime +
                ", vTopic=" + vTopic +
                ", vNote='" + vNote + '\'' +
                ", vLetter='" + vLetter + '\'' +
                ", vRecycled=" + vRecycled +
                ", vDirector='" + vDirector + '\'' +
                ", vEnname='" + vEnname + '\'' +
                ", vLang='" + vLang + '\'' +
                ", vScore=" + vScore +
                ", vScorenum=" + vScorenum +
                ", vNickname='" + vNickname + '\'' +
                ", vReweek='" + vReweek + '\'' +
                ", vMtime=" + vMtime +
                ", vImdb=" + vImdb +
                ", vDayhit=" + vDayhit +
                ", vWeekhit=" + vWeekhit +
                ", vMonthhit=" + vMonthhit +
                ", vDaytime=" + vDaytime +
                ", vWeektime=" + vWeektime +
                ", vMonthtime=" + vMonthtime +
                ", vLen='" + vLen + '\'' +
                ", vTotal='" + vTotal + '\'' +
                ", typeName='" + typeName + '\'' +
                '}';
    }

    public Integer getvId() {
        return vId;
    }

    public void setvId(Integer vId) {
        this.vId = vId;
    }

    public Short getTid() {
        return tid;
    }

    public void setTid(Short tid) {
        this.tid = tid;
    }

    public String getvName() {
        return vName;
    }

    public void setvName(String vName) {
        this.vName = vName;
    }

    public Integer getvState() {
        return vState;
    }

    public void setvState(Integer vState) {
        this.vState = vState;
    }

    public String getvPic() {
        return vPic;
    }

    public void setvPic(String vPic) {
        this.vPic = vPic;
    }

    public Integer getvHit() {
        return vHit;
    }

    public void setvHit(Integer vHit) {
        this.vHit = vHit;
    }

    public Short getvRank() {
        return vRank;
    }

    public void setvRank(Short vRank) {
        this.vRank = vRank;
    }

    public String getvActor() {
        return vActor;
    }

    public void setvActor(String vActor) {
        this.vActor = vActor;
    }

    public Integer getvPublishyear() {
        return vPublishyear;
    }

    public void setvPublishyear(Integer vPublishyear) {
        this.vPublishyear = vPublishyear;
    }

    public String getvPublisharea() {
        return vPublisharea;
    }

    public void setvPublisharea(String vPublisharea) {
        this.vPublisharea = vPublisharea;
    }

    public Integer getvAddtime() {
        return vAddtime;
    }

    public void setvAddtime(Integer vAddtime) {
        this.vAddtime = vAddtime;
    }

    public Integer getvTopic() {
        return vTopic;
    }

    public void setvTopic(Integer vTopic) {
        this.vTopic = vTopic;
    }

    public String getvNote() {
        return vNote;
    }

    public void setvNote(String vNote) {
        this.vNote = vNote;
    }

    public String getvLetter() {
        return vLetter;
    }

    public void setvLetter(String vLetter) {
        this.vLetter = vLetter;
    }

    public Short getvRecycled() {
        return vRecycled;
    }

    public void setvRecycled(Short vRecycled) {
        this.vRecycled = vRecycled;
    }

    public String getvDirector() {
        return vDirector;
    }

    public void setvDirector(String vDirector) {
        this.vDirector = vDirector;
    }

    public String getvEnname() {
        return vEnname;
    }

    public void setvEnname(String vEnname) {
        this.vEnname = vEnname;
    }

    public String getvLang() {
        return vLang;
    }

    public void setvLang(String vLang) {
        this.vLang = vLang;
    }

    public Integer getvScore() {
        return vScore;
    }

    public void setvScore(Integer vScore) {
        this.vScore = vScore;
    }

    public Integer getvScorenum() {
        return vScorenum;
    }

    public void setvScorenum(Integer vScorenum) {
        this.vScorenum = vScorenum;
    }

    public String getvNickname() {
        return vNickname;
    }

    public void setvNickname(String vNickname) {
        this.vNickname = vNickname;
    }

    public String getvReweek() {
        return vReweek;
    }

    public void setvReweek(String vReweek) {
        this.vReweek = vReweek;
    }

    public Float getvMtime() {
        return vMtime;
    }

    public void setvMtime(Float vMtime) {
        this.vMtime = vMtime;
    }

    public Float getvImdb() {
        return vImdb;
    }

    public void setvImdb(Float vImdb) {
        this.vImdb = vImdb;
    }

    public Integer getvDayhit() {
        return vDayhit;
    }

    public void setvDayhit(Integer vDayhit) {
        this.vDayhit = vDayhit;
    }

    public Integer getvWeekhit() {
        return vWeekhit;
    }

    public void setvWeekhit(Integer vWeekhit) {
        this.vWeekhit = vWeekhit;
    }

    public Integer getvMonthhit() {
        return vMonthhit;
    }

    public void setvMonthhit(Integer vMonthhit) {
        this.vMonthhit = vMonthhit;
    }

    public Integer getvDaytime() {
        return vDaytime;
    }

    public void setvDaytime(Integer vDaytime) {
        this.vDaytime = vDaytime;
    }

    public Integer getvWeektime() {
        return vWeektime;
    }

    public void setvWeektime(Integer vWeektime) {
        this.vWeektime = vWeektime;
    }

    public Integer getvMonthtime() {
        return vMonthtime;
    }

    public void setvMonthtime(Integer vMonthtime) {
        this.vMonthtime = vMonthtime;
    }

    public String getvLen() {
        return vLen;
    }

    public void setvLen(String vLen) {
        this.vLen = vLen;
    }

    public String getvTotal() {
        return vTotal;
    }

    public void setvTotal(String vTotal) {
        this.vTotal = vTotal;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}
