package com.pipimovie.service.businessobject;

import java.util.List;

public class TypeBO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_type.tid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_type.upid
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Byte upid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_type.tname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_type.tenname
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private String tenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_type.torder
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Integer torder;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sea_type.ishidden
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    private Short ishidden;

    private List<TypeBO> children;

    private List<VideoBO> videoBOList;

    public List<VideoBO> getVideoBOList() {
        return videoBOList;
    }

    public void setVideoBOList(List<VideoBO> videoBOList) {
        this.videoBOList = videoBOList;
    }

    public List<TypeBO> getChildren() {
        return children;
    }

    public void setChildren(List<TypeBO> children) {
        this.children = children;
    }

    public Short getTid() {
        return tid;
    }

    public void setTid(Short tid) {
        this.tid = tid;
    }

    public Byte getUpid() {
        return upid;
    }

    public void setUpid(Byte upid) {
        this.upid = upid;
    }

    public String getTname() {
        return tname;
    }

    public void setTname(String tname) {
        this.tname = tname;
    }

    public String getTenname() {
        return tenname;
    }

    public void setTenname(String tenname) {
        this.tenname = tenname;
    }

    public Integer getTorder() {
        return torder;
    }

    public void setTorder(Integer torder) {
        this.torder = torder;
    }

    public Short getIshidden() {
        return ishidden;
    }

    public void setIshidden(Short ishidden) {
        this.ishidden = ishidden;
    }
}
