package com.pipimovie.dao;

import com.pipimovie.dataobject.CCKDO;

public interface CCKDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_cck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_cck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(CCKDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_cck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(CCKDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_cck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    CCKDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_cck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(CCKDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_cck
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(CCKDO record);
}