package com.pipimovie.dao;

import com.pipimovie.dataobject.CodataDO;
import com.pipimovie.dataobject.CodataDOWithBLOBs;

public interface CodataDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_data
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_data
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(CodataDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_data
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(CodataDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_data
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    CodataDOWithBLOBs selectByPrimaryKey(Integer vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_data
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(CodataDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_data
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(CodataDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_data
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(CodataDO record);
}