package com.pipimovie.dao;

import com.pipimovie.dataobject.CofiltersDO;

public interface CofiltersDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_filters
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_filters
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(CofiltersDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_filters
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(CofiltersDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_filters
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    CofiltersDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_filters
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(CofiltersDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_filters
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(CofiltersDO record);
}