package com.pipimovie.dao;

import com.pipimovie.dataobject.ConewsDO;

public interface ConewsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_news
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_news
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(ConewsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_news
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(ConewsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_news
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    ConewsDO selectByPrimaryKey(Integer nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_news
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(ConewsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_news
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(ConewsDO record);
}