package com.pipimovie.dao;

import com.pipimovie.dataobject.ContentDO;

public interface ContentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(ContentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(ContentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    ContentDO selectByPrimaryKey(Integer vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(ContentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ContentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_content
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(ContentDO record);
}