package com.pipimovie.dao;

import com.pipimovie.dataobject.CotypeDO;

public interface CotypeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(CotypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(CotypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    CotypeDO selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(CotypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_type
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(CotypeDO record);
}