package com.pipimovie.dao;

import com.pipimovie.dataobject.CountDO;

public interface CountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_count
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_count
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(CountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_count
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(CountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_count
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    CountDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_count
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(CountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_count
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(CountDO record);
}