package com.pipimovie.dao;

import com.pipimovie.dataobject.CourlDO;

public interface CourlDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_url
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_url
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(CourlDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_url
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(CourlDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_url
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    CourlDO selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_url
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(CourlDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_co_url
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(CourlDO record);
}