package com.pipimovie.dao;

import com.pipimovie.dataobject.ErraddDO;

public interface ErraddDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_erradd
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(ErraddDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_erradd
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(ErraddDO record);
}