package com.pipimovie.dao;

import com.pipimovie.dataobject.FavoriteDO;

public interface FavoriteDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_favorite
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_favorite
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(FavoriteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_favorite
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(FavoriteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_favorite
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    FavoriteDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_favorite
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(FavoriteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_favorite
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(FavoriteDO record);
}