package com.pipimovie.dao;

import com.pipimovie.dataobject.FlinkDO;

public interface FlinkDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_flink
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_flink
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(FlinkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_flink
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(FlinkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_flink
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    FlinkDO selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_flink
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(FlinkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_flink
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(FlinkDO record);
}