package com.pipimovie.dao;

import com.pipimovie.dataobject.IEDO;

public interface IEDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_ie
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_ie
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(IEDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_ie
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(IEDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_ie
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    IEDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_ie
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(IEDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_ie
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(IEDO record);
}