package com.pipimovie.dao;

import com.pipimovie.dataobject.JqtypeDO;

public interface JqtypeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_jqtype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Short tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_jqtype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(JqtypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_jqtype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(JqtypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_jqtype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    JqtypeDO selectByPrimaryKey(Short tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_jqtype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(JqtypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_jqtype
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(JqtypeDO record);
}