package com.pipimovie.dao;

import com.pipimovie.dataobject.MemberDO;

public interface MemberDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    MemberDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(MemberDO record);
}