package com.pipimovie.dao;

import com.pipimovie.dataobject.MemberGroupDO;

public interface MemberGroupDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member_group
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member_group
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(MemberGroupDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member_group
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(MemberGroupDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member_group
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    MemberGroupDO selectByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member_group
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(MemberGroupDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_member_group
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(MemberGroupDO record);
}