package com.pipimovie.dao;

import com.pipimovie.dataobject.MyadDO;

public interface MyadDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_myad
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_myad
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(MyadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_myad
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(MyadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_myad
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    MyadDO selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_myad
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(MyadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_myad
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(MyadDO record);
}