package com.pipimovie.dao;

import com.pipimovie.dataobject.MytagDO;

public interface MytagDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_mytag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_mytag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(MytagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_mytag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(MytagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_mytag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    MytagDO selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_mytag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(MytagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_mytag
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(MytagDO record);
}