package com.pipimovie.dao;

import com.pipimovie.dataobject.SearchKeywordsDO;

public interface SearchKeywordsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_search_keywords
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_search_keywords
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(SearchKeywordsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_search_keywords
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(SearchKeywordsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_search_keywords
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    SearchKeywordsDO selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_search_keywords
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(SearchKeywordsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_search_keywords
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(SearchKeywordsDO record);
}