package com.pipimovie.dao;

import com.pipimovie.dataobject.TagsDO;

public interface TagsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer tagid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(TagsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(TagsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    TagsDO selectByPrimaryKey(Integer tagid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(TagsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_tags
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(TagsDO record);
}