package com.pipimovie.dao;

import com.pipimovie.dataobject.TempDO;

public interface TempDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_temp
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_temp
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(TempDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_temp
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(TempDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_temp
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    TempDO selectByPrimaryKey(Integer vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_temp
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(TempDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_temp
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(TempDO record);
}