package com.pipimovie.dao;

import com.pipimovie.dataobject.TopicDO;

public interface TopicDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(TopicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(TopicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    TopicDO selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(TopicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_topic
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(TopicDO record);
}