package com.pipimovie.dao;

import com.pipimovie.dataobject.ZykDO;

public interface ZykDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_zyk
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_zyk
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insert(ZykDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_zyk
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int insertSelective(ZykDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_zyk
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    ZykDO selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_zyk
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKeySelective(ZykDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sea_zyk
     *
     * @mbg.generated Wed Jun 24 11:20:32 CST 2020
     */
    int updateByPrimaryKey(ZykDO record);
}